### ISSUE TITLE
[1.16.1] Crashing with SuperAxes-1.16.1-1.1.4

### ISSUE THREAD

**Issue by InsaanNotFound** [gbl/EasierVillagerTrading#17]
**Crash report:**

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'lvmnt'!
    at Not Enough Crashes deobfuscated stack trace.(1.16.1+build.21)
    at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
    at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
    at net.minecraft.client.MinecraftClient.redirect$bne000$stopFabricInit(MinecraftClient:10791)
    at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:425)
    at net.minecraft.client.main.Main.main(Main:177)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
    at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
    at org.multimc.EntryPoint.listen(EntryPoint.java:143)
    at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.RuntimeException: Attempted to register object blackstone_superaxe twice! (at raw IDs 5298 and 15219 )
    at net.minecraft.util.registry.SimpleRegistry.handler$zka000$setPre(SimpleRegistry:635)
    at net.minecraft.util.registry.SimpleRegistry.set(SimpleRegistry)
    at net.minecraft.util.registry.DefaultedRegistry.set(DefaultedRegistry:27)
    at net.minecraft.util.registry.SimpleRegistry.add(SimpleRegistry:69)
    at net.minecraft.util.registry.Registry.register(Registry:359)
    at com.github.levoment.superaxes.Items.ModItems.lambda$registerItems$0(ModItems.java:48)
    at java.util.HashMap.forEach(Unknown Source)
    at com.github.levoment.superaxes.Items.ModItems.registerItems(ModItems.java:48)
    at com.github.levoment.superaxes.SuperAxesMod.onInitialize(SuperAxesMod.java:38)
    at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
    ... 19 more

Issue only happens when both _(easiervillagertrading-1.16-fabric0.13.1-1.5.1.jar) and ([1.16.1]+SuperAxes-1.1.4.jar)_ are present in mod folder. FApi-0.17.0+build.386-1.16.1.jar with Fabric Loader 0.9.1+build205. I would be thankful for a fix. It seems game registers specific item twice, though it is weird as this mod does not add items.

**Comment by gbl** [comment]
Sorry, can't reproduce; it doesn't crash for me when I have this list of mods (and nothing else):

```
'[1.16.1]+SuperAxes-1.1.4.jar'
 easiervillagertrading-1.16-fabric0.13.1-1.5.1.jar
 fabric-api-0.17.0+build.386-1.16.1.jar
 modmenu-1.12.2+build.16.jar
```

As the relevant error message is
`Caused by: java.lang.RuntimeException: Attempted to register object blackstone_superaxe twice! (at raw IDs 5298 and 15219 )`,
could it be that you have another mod that registers an item with the same name, but one mod checks if it already exists and the other one doesn't? In that case, mod load order would make a difference, and having another mod (mine) could change the load order.

**Comment by InsaanNotFound** [comment]
This was a bad conflict between SuperAxes and BlackstoneTools, which have superaxe compat. It seems it depended on load order. I just downgraded BlackstoneTools to version where superaxe compat would not be there, and everything was fine. Closing as resolved.
